# vCenter Details
vcenter_server              = "vcenter.domain.tld"
vcenter_username            = "administrator@vsphere.local"
vcenter_password            = "password"
vcenter_insecure_connection = false
vcenter_cluster             = "cluster"
vcenter_resource_pool       = "pool"
vcenter_datastore           = "datastore"
vcenter_folder              = "templates"
